"""Builds the pin icon sheet, its numbered reference copy, and the PinIcon enum.

    python tools/build_sheet.py

src/Assets/icons/order.txt is the single source of truth: one icon name per line,
in index order, each matching a 128x128 PNG beside it. The enum is generated from
that same list rather than maintained by hand, because an enum that disagrees with
the sheet writes the wrong icon into people's save files.
"""
import os

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ICONS = os.path.join(ROOT, "src", "Assets", "icons")
SHEET = os.path.join(ROOT, "src", "Assets", "pin_icons.png")
NUMBERED = os.path.join(ROOT, "src", "Assets", "pin_icons_numbered.png")
ENUM = os.path.join(ROOT, "src", "PinIcon.cs")

CELL = 128
COLUMNS = 10

names = [n.strip() for n in open(os.path.join(ICONS, "order.txt")) if n.strip()]
rows = (len(names) + COLUMNS - 1) // COLUMNS

sheet = Image.new("RGBA", (COLUMNS * CELL, rows * CELL), (0, 0, 0, 0))
for i, name in enumerate(names):
    tile = Image.open(os.path.join(ICONS, name + ".png")).convert("RGBA")
    if tile.size != (CELL, CELL):
        tile = tile.resize((CELL, CELL), Image.LANCZOS)
    sheet.paste(tile, ((i % COLUMNS) * CELL, (i // COLUMNS) * CELL))
sheet.save(SHEET, "PNG")
print(f"{SHEET} {sheet.size} ({len(names)} icons, {rows} rows)")

# Reference copy: same grid on a dark ground with each index drawn on it, so a number
# in the config file can be looked up without counting cells.
numbered = Image.new("RGBA", sheet.size, (24, 24, 24, 255))
numbered.alpha_composite(sheet)
draw = ImageDraw.Draw(numbered)
for i in range(len(names)):
    x, y = (i % COLUMNS) * CELL, (i // COLUMNS) * CELL
    draw.rectangle([x, y, x + CELL - 1, y + CELL - 1], outline=(70, 70, 70, 255))
    draw.text((x + 4, y + 3), str(i), fill=(255, 190, 90, 255))
numbered.convert("RGB").save(NUMBERED, "PNG")
print(f"{NUMBERED} {numbered.size}")


def pascal(name):
    return "".join(part.capitalize() for part in name.split("_"))


lines = [
    "// Generated by tools/build_sheet.py from src/Assets/icons/order.txt - do not edit by hand.",
    "namespace CarturMapPins",
    "{",
    "    /// The custom icon sheet, named. Bound as an enum rather than an int so the settings screen",
    "    /// renders a dropdown of recognisable names instead of a slider you drag from -1 to "
    f"{len(names) - 1}.",
    "    ///",
    "    /// Values are the sprite index in Assets/pin_icons_numbered.png. They are what gets written",
    "    /// to the config file and resolved to a sprite at runtime, so reordering order.txt silently",
    "    /// repoints every saved setting - append instead.",
    "    public enum PinIcon",
    "    {",
    "        Default = -1,",
]
seen = set()
for i, name in enumerate(names):
    member = pascal(name)
    assert member not in seen, f"duplicate enum member {member}"
    seen.add(member)
    lines.append(f"        {member} = {i},")
lines += ["    }", "}", ""]

with open(ENUM, "w", newline="\n") as f:
    f.write("\n".join(lines))
print(f"{ENUM} ({len(names)} members)")
