namespace CarturMapPins
{
    /// The custom icon sheet, named. Bound as an enum rather than an int so the settings screen
    /// renders a dropdown of recognisable names instead of a slider you drag from -1 to 82.
    ///
    /// Values are the sprite index in Assets/pin_icons_numbered.png and must not be renumbered -
    /// they are what gets written to the config file and resolved to a sprite at runtime.
    public enum PinIcon
    {
        Default = -1,
        Dot = 0,
        CrossedSticks = 1,
        SeekerHead = 2,
        Pillars = 3,
        MushroomTree = 4,
        Bed = 5,
        Bee = 6,
        Talon = 7,
        Boar = 8,
        SkullAndBones = 9,
        TrollSkull = 10,
        Crystal = 11,
        Campfire = 12,
        Tent = 13,
        Bell = 14,
        Coins = 15,
        Castle = 16,
        FortressAssault = 17,
        Golem = 18,
        Chicken = 19,
        Door = 20,
        DragonEgg = 21,
        CobwebArch = 22,
        Skull = 23,
        Pickaxe = 24,
        FishBones = 25,
        Signpost = 26,
        Longship = 27,
        StoneArch = 28,
        DvergrHead = 29,
        StandingStone = 30,
        Imp = 31,
        Ember = 32,
        Fish = 33,
        Shrine = 34,
        Blob = 35,
        Berries = 36,
        Sprout = 37,
        TowerDoor = 38,
        Arrowhead = 39,
        Swimmer = 40,
        House = 41,
        DiveArrow = 42,
        Island = 43,
        Chalice = 44,
        TreasureChest = 45,
        LockedTower = 46,
        MineFace = 47,
        Nest = 48,
        Leaf = 49,
        FulingFace = 50,
        OpenChest = 51,
        OreCluster = 52,
        MysteryBox = 53,
        Pig = 54,
        Tombstone = 55,
        WizardHat = 56,
        SkeletalHand = 57,
        Boulder = 58,
        SerpentHead = 59,
        NeedleAndThread = 60,
        SwordAndSpear = 61,
        SinkingShip = 62,
        SailingBoat = 63,
        Tree = 64,
        Rubble = 65,
        Hide = 66,
        Fort = 67,
        BrickWall = 68,
        SwordAndShovel = 69,
        Tick = 70,
        Gravestone = 71,
        TotemPole = 72,
        GiantSkull = 73,
        MineTower = 74,
        Antlers = 75,
        DrakeHead = 76,
        Banner = 77,
        Armour = 78,
        Village = 79,
        LogCabin = 80,
        Canoe = 81,
        SignBoard = 82,
    }
}
